# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
   Pages:
    sort:
      key: surname
    sort_options:
      - key: surname
      - key: surname
        order: desc
      - key: start_date
        label: Longest employed first
    subtext_key: role
    image_key: profile_image
    image_size: cover
    singular_name: Staff Member
    singular_key: staff_member
    disable_add: false
    icon: people
    description: Collection of staff members.
    documentation:
      url: https://example.com/documentation
      text: Read the documentation here.
    add_options:
      - name: Add Staff Member
        icon: person_add
    filter:
      exclude:
        - secret.yml

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:
   
    

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: data
  collections: themes/netlify-basic/content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: themes/netlify-basic;
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: &#39;&#39;

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC
