# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
   Attorney:
    create:
          path: 'content/attorneys/{slug}.md'    
    sort:
      key: surname
    sort_options:
      - key: surname
      - key: surname
        order: desc
      - key: start_date
        label: Longest employed first
    subtext_key: role
    image_key: profile_image
    image_size: cover
    singular_name: Attorney
    singular_key: attorney
    disable_add: false
    icon: people
    description: All Attorneys.
    path: content/attorneys
    secrets:
     path: content/attorneys
    add_options:
      - name: Add Attorney
        editor: content
        icon: person_add
    _inputs:
      title:
       label: Name
      src:
       label: Featured Image     
       type: image
      banner:
       label: Banner Image     
       type: image
      frontimg:
       label: Attorneys Page Image
       type: image       
      
   Blogs:
    create:
          path: '{slug}.md'    
    singular_name: Post
    singular_key: post
    disable_add: false
    icon: edit_document
    description: All blogs.
    path: content/blog
    secrets:
     path: content/blog
    add_options:
      - name: Add Post
        editor: content
        icon: person_add
    filter:
      exclude:
        - secret.yml

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:
   
    

# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source: themes/netlify-basic

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC
