baseURL = 'https://fair-puddle.cloudvent.net/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Free Consultation | San Diego Criminal Defense Lawyer'
theme = 'netlify-basic'
[params]
  hostName = 'https://fair-puddle.cloudvent.net'
  name = 'Criminal Defense Attorney San Diego'
  site_description = "Sevens Legal, APC"
  author = 'sevenslegal'
[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']
  publishDate = ['publishDate', 'date']
[markup.goldmark.parser.attribute]
block = true
title = true
[taxonomies]
    category = "categories"
    tag = "tags"
[permalinks]
  categories =  '/:slug/'
[menu]
[[menu.main]]
    name = "Home"
    identifier = "home"
	weight = -150
    url = "/"
[[menu.main]]
    name = "Attorneys"
    identifier = "attorneys"
	weight = -140
    url = "/sevens-legal-attorneys/"
[[menu.main]]
    name = "Criminal Law"
	weight = -130
    url = "/criminal-lawyer/"
[[menu.main]]
weight = -120
    name = "Testimonials"
    url = "/testimonials/"
[[menu.main]]
    name = "Blog"
	weight = -110
    url = "/blog/"
[[menu.main]]
weight = -100
    name = "Contact"
    url = "/contact/"

    [outputFormats]
  [outputFormats.WebAppManifest]
      mediaType = "application/manifest+json"
        rel = "manifest"
    [outputFormats.RSS]
        baseName = "rss"
    [outputFormats.IMAGESSITEMAP]
  MediaType              = "application/xml"
  BaseName               = "imagessitemap"
  isPlainText            = false
  isHTML                 = false
  noUgly                 = true
  permalinkable          = false

[outputs]
    home = ["HTML", "RSS", "JSON", "WebAppManifest", "IMAGESSITEMAP"]
    page = ["HTML"]
    section = ["HTML","RSS"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]